### ISSUE TITLE
Tutorial: Can it pause?

### ISSUE THREAD

**Issue by hancandy** [Putaitu/idle-skat#20]
Can we introduce the different information one by one, or at least let players check the information again after the game has started?

**Comment by mrzapp** [comment]
Make dialogs appear at the event instead of all at once:

| Name | Open | Close |
|----------|----------|----------|
| Produce | Start | Press button |
| Transfer money (PA & CA) | Start | Press button |
| Time control | Start | Press play button |
| Pay B tax | Notification | Press button |
| Quests | Day 10 | Click OK |
| Report VAT | Notification | Press button |
| Price | Quest complete | Change price |
| Machines | Quest complete | Buy machine |
